<?php

namespace ContainerPHPsuhK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NNiAw0GService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nNiAw0G' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nNiAw0G'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'etudiant' => ['privates', '.errored..service_locator.nNiAw0G.App\\Entity\\Etudiant', NULL, 'Cannot autowire service ".service_locator.nNiAw0G": it references class "App\\Entity\\Etudiant" but no such service exists.'],
        ], [
            'etudiant' => 'App\\Entity\\Etudiant',
        ]);
    }
}
